<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20150713 23:45:50.602" generator="Robot 2.8.7 (Python 2.7.6 on darwin)">
<suite source="/Users/Sudarsh/project/demoapp/login_tests/valid_login.txt" id="s1" name="Valid Login">
<test id="s1-t1" name="Valid Login">
<kw type="kw" name="resource.Open Browser To Login Page">
<doc></doc>
<arguments>
</arguments>
<kw type="kw" name="Open Browser">
<doc></doc>
<arguments>
<arg>${LOGIN URL}</arg>
<arg>${BROWSER}</arg>
</arguments>
<msg timestamp="20150713 23:45:50.655" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" endtime="20150713 23:45:50.655" starttime="20150713 23:45:50.654"></status>
</kw>
<status status="FAIL" endtime="20150713 23:45:50.655" starttime="20150713 23:45:50.652"></status>
</kw>
<kw type="teardown" name="Close Browser">
<doc></doc>
<arguments>
</arguments>
<msg timestamp="20150713 23:45:50.657" level="FAIL">No keyword with name 'Close Browser' found.</msg>
<status status="FAIL" endtime="20150713 23:45:50.657" starttime="20150713 23:45:50.657">No keyword with name 'Close Browser' found.</status>
</kw>
<doc></doc>
<tags>
</tags>
<status status="FAIL" endtime="20150713 23:45:50.657" critical="yes" starttime="20150713 23:45:50.651">No keyword with name 'Open Browser' found.

Also teardown failed:
No keyword with name 'Close Browser' found.</status>
</test>
<doc>A test suite with a single test for valid login.

This test has a workflow that is created using keywords in
the imported resource file.</doc>
<metadata>
</metadata>
<status status="FAIL" endtime="20150713 23:45:50.658" starttime="20150713 23:45:50.602"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" pass="0" id="s1" name="Valid Login">Valid Login</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20150713 23:45:50.648" level="ERROR">Error in file '/Users/Sudarsh/project/demoapp/login_tests/resource.txt': Importing test library 'Selenium2Library' failed: ImportError: No module named Selenium2Library
Traceback (most recent call last):
  None
PYTHONPATH:
  /Library/Python/2.7/site-packages/robot/libraries
  /Library/Python/2.7/site-packages
  /usr/local/bin
  /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages
  /usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_carbon
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
  /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
  /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC
  /usr/local/lib/wxPython-3.0.2.0/lib/python2.7
  .
  /Users/Sudarsh/project/demoapp/login_tests</msg>
</errors>
</robot>
